export const CURRENCY_CODES = {
  'USD': '$',
  'EUR': '€',
  'GBP': '£',
  'CAD': 'CAD $',
  'AFN': 'AFN ؋',
  'ALL': 'ALL',
  'DZD': 'DZD',
  'AOA': 'AOA Kz',
  'ARS': 'ARS $',
  'AMD': 'AMD ֏',
  'AWG': 'AWG',
  'AUD': 'AUD $',
  'BBD': 'BBD $',
  'AZN': 'AZN ₼',
  'BDT': 'BDT ৳',
  'BSD': 'BSD $',
  'BHD': 'BHD',
  'BIF': 'BIF',
  'BYN': 'BYN',
  'BZD': 'BZD $',
  'BMD': 'BMD $',
  'BTN': 'BTN',
  'BAM': 'BAM KM',
  'BRL': 'BRL R$',
  'BOB': 'BOB Bs',
  'BWP': 'BWP P',
  'BND': 'BND $',
  'BGN': 'BGN',
  'MMK': 'MMK K',
  'KHR': 'KHR ៛',
  'CVE': 'CVE',
  'KYD': 'KYD $',
  'XAF': 'XAF FCFA',
  'CLP': 'CLP $',
  'CNY': 'CNY ¥',
  'COP': 'COP $',
  'KMF': 'KMF CF',
  'CDF': 'CDF',
  'CRC': 'CRC ₡',
  'HRK': 'HRK kn',
  'CZK': 'CZK Kč',
  'DKK': 'DKK kr',
  'DJF': 'DJF',
  'DOP': 'DOP $',
  'XCD': 'XCD $',
  'EGP': 'EGP E£',
  'ERN': 'ERN',
  'ETB': 'ETB',
  'FKP': 'FKP £',
  'XPF': 'XPF CFPF',
  'FJD': 'FJD $',
  'GIP': 'GIP £',
  'GMD': 'GMD',
  'GHS': 'GHS ₵',
  'GTQ': 'GTQ Q',
  'GYD': 'GYD $',
  'GEL': 'GEL ₾',
  'GNF': 'GNF FG',
  'HTG': 'HTG',
  'HNL': 'HNL L',
  'HKD': 'HKD HK$',
  'HUF': 'HUF Ft',
  'ISK': 'ISK kr',
  'INR': 'INR ₹',
  'IDR': 'IDR Rp',
  'ILS': 'ILS ₪',
  'IRR': 'IRR',
  'IQD': 'IQD',
  'JMD': 'JMD $',
  'JPY': 'JPY ¥',
  'JEP': 'JEP',
  'JOD': 'JOD',
  'KZT': 'KZT ₸',
  'KES': 'KES',
  'KID': 'KID',
  'KWD': 'KWD',
  'KGS': 'KGS',
  'LAK': 'LAK ₭',
  'LVL': 'LVL',
  'LBP': 'LBP L£',
  'LSL': 'LSL',
  'LRD': 'LRD $',
  'LYD': 'LYD',
  'LTL': 'LTL',
  'MGA': 'MGA Ar',
  'MKD': 'MKD',
  'MOP': 'MOP',
  'MWK': 'MWK',
  'MVR': 'MVR',
  'MRU': 'MRU',
  'MXN': 'MXN $',
  'MYR': 'MYR RM',
  'MUR': 'MUR Rs',
  'MDL': 'MDL',
  'MAD': 'MAD',
  'MNT': 'MNT ₮',
  'MZN': 'MZN',
  'NAD': 'NAD $',
  'NPR': 'NPR Rs',
  'ANG': 'ANG',
  'NZD': 'NZD $',
  'NIO': 'NIO C$',
  'NGN': 'NGN ₦',
  'NOK': 'NOK kr',
  'OMR': 'OMR',
  'PAB': 'PAB',
  'PKR': 'PKR Rs',
  'PGK': 'PGK',
  'PYG': 'PYG ₲',
  'PEN': 'PEN',
  'PHP': 'PHP ₱',
  'PLN': 'PLN zł',
  'QAR': 'QAR',
  'RON': 'RON lei',
  'RUB': 'RUB ₽',
  'RWF': 'RWF RF',
  'WST': 'WST',
  'SHP': 'SHP £',
  'SAR': 'SAR',
  'RSD': 'RSD',
  'SCR': 'SCR',
  'SLL': 'SLL',
  'SGD': 'SGD $',
  'SDG': 'SDG',
  'SOS': 'SOS',
  'SYP': 'SYP £',
  'ZAR': 'ZAR R',
  'KRW': 'KRW ₩',
  'SSP': 'SSP £',
  'SBD': 'SBD $',
  'LKR': 'LKR Rs',
  'SRD': 'SRD $',
  'SZL': 'SZL',
  'SEK': 'SEK kr',
  'CHF': 'CHF',
  'TWD': 'TWD $',
  'THB': 'THB ฿',
  'TJS': 'TJS',
  'TZS': 'TZS',
  'TOP': 'TOP T$',
  'TTD': 'TTD $',
  'TND': 'TND',
  'TRY': '₺',
  'TMT': 'TMT',
  'UGX': 'UGX',
  'UAH': 'UAH ₴',
  'AED': 'AED',
  'UYU': 'UYU $',
  'UZS': 'UZS',
  'VUV': 'VUV',
  'VES': 'VES',
  'VND': 'VND ₫',
  'XOF': 'XOF F CFA',
  'YER': 'YER',
  'ZMW': 'ZMW ZK',
  'BYR': 'BYR',
  'STD': 'STD',
  'STN': 'STN Db',
  'VEF': 'VEF',
  'VED': 'VED'
}